In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec

In [3]:
import gensim.downloader as api

info = api.info()
corpus = api.load('text8')
#corpusFake =api.load('fake-news')
model = Word2Vec(corpus)  # train a model from the corpus

model.save("text8_trained")

model.wv.save_word2vec_format("text8_trained_format")

c = gensim.models.Word2Vec.load_word2vec_format("w2v_of_heb_format_utf8")

In [4]:
c = gensim.models.KeyedVectors.load_word2vec_format("w2v_of_heb_format_utf8")

In [5]:
model = gensim.models.KeyedVectors.load_word2vec_format("text8_trained_format")

In [6]:
type(c)

gensim.models.keyedvectors.Word2VecKeyedVectors

In [7]:
c.vectors

array([[-0.24624045, -0.2587168 , -0.5152275 , ...,  0.9750343 ,
        -1.1474545 , -0.6491565 ],
       [-0.13589075, -1.8688356 ,  0.2275602 , ...,  1.5796703 ,
         4.0348005 , -0.9181242 ],
       [-1.5275495 , -1.0684487 , -1.1158944 , ..., -0.7411685 ,
        -0.29557168,  0.3551615 ],
       ...,
       [ 0.05715663,  0.0574713 , -0.09818605, ...,  0.01154051,
         0.05566889, -0.00515166],
       [ 0.00525682,  0.05785046, -0.02618515, ..., -0.04403783,
        -0.03846656,  0.01925667],
       [ 0.16295129,  0.10678402, -0.11366634, ..., -0.02172237,
         0.01325501,  0.11741671]], dtype=float32)

In [8]:
c.most_similar("תורה",topn=100)

[("תור'", 0.8901426196098328),
 ('התורה', 0.6567139625549316),
 ('שהתורה', 0.6273691654205322),
 ('מתורה', 0.6145460605621338),
 ('תורתינו', 0.6138904094696045),
 ('והתורה', 0.60987788438797),
 ('תורתנו', 0.6078733205795288),
 ('תוה"ק', 0.5979991555213928),
 ('דהתורה', 0.5875756740570068),
 ('שתורה', 0.568619966506958),
 ('דתורה', 0.5614792108535767),
 ('התוה"ק', 0.5547425150871277),
 ('תורה"', 0.5534633994102478),
 ('סופרים', 0.5465327501296997),
 ('ד"ת', 0.5237507820129395),
 ('אגדה', 0.5067740678787231),
 ('תנ"ך', 0.5008599162101746),
 ("התור'", 0.5004966259002686),
 ('תושבע"פ', 0.48622986674308777),
 ('ותורה', 0.48276519775390625),
 ('תוכחה', 0.4764705300331116),
 ('מינות', 0.47330158948898315),
 ("שהתור'", 0.47281011939048767),
 ('חכמים', 0.4706379473209381),
 ('תוכחות', 0.46972572803497314),
 ('והיתר', 0.46712160110473633),
 ('חז"ל', 0.46614691615104675),
 ('חכמה', 0.46091535687446594),
 ('התוכחה', 0.4594120979309082),
 ("סופרי'", 0.4570969343185425),
 ('כשהתורה', 0.4557516574859

In [9]:
c.most_similar('חז"ל')

[('חכז"ל', 0.8929444551467896),
 ('רז"ל', 0.879279375076294),
 ('חכמים', 0.8774027824401855),
 ("חכמי'", 0.8162449598312378),
 ('ריב"ז', 0.6403717398643494),
 ('אושא', 0.6362330913543701),
 ('דחז"ל', 0.6305602788925171),
 ('השבים', 0.6245054006576538),
 ('שחז"ל', 0.6223561763763428),
 ('וחז"ל', 0.6177453398704529)]

In [10]:
c.wv.most_similar('השי"ת')

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('הבורא', 0.8526402115821838),
 ('ית"ש', 0.8256053328514099),
 ("ית'", 0.825182318687439),
 ('הי"ת', 0.8016533851623535),
 ('יתברך', 0.791447639465332),
 ('הש"י', 0.7855501174926758),
 ('שהשי"ת', 0.7754173278808594),
 ('תפלתינו', 0.765521764755249),
 ('האל', 0.7619894742965698),
 ('בוראו', 0.7531489729881287)]

In [11]:
c.most_similar("תלמוד",topn=100)

[('מתלמוד', 0.6331462264060974),
 ('שתלמוד', 0.6308479905128479),
 ('ותלמוד', 0.6201453804969788),
 ('דתלמוד', 0.5987375974655151),
 ('כשולחן', 0.5950429439544678),
 ('כשלחן', 0.5743714570999146),
 ('כתלמוד', 0.5335820913314819),
 ('וללמוד', 0.5128160715103149),
 ('לתלמוד', 0.5086691379547119),
 ('לימוד', 0.5064773559570312),
 ('הלומד', 0.4766457676887512),
 ('דהשלחן', 0.474860280752182),
 ('לאמיתה', 0.4738258719444275),
 ('גמרא', 0.46819543838500977),
 ('שבשלחן', 0.46802347898483276),
 ('לגמרא', 0.4641278386116028),
 ('מדרש', 0.4612939953804016),
 ('ש"ס', 0.4570014476776123),
 ('שנון', 0.4557696282863617),
 ('עיון', 0.4543495774269104),
 ('והשולחן', 0.45372578501701355),
 ('חזוק', 0.4526903033256531),
 ('למוד', 0.4483669698238373),
 ('עיונא', 0.4462047815322876),
 ('לאמתה', 0.4421282410621643),
 ('בשולחן', 0.44211941957473755),
 ('ביאור', 0.4394286274909973),
 ('להתלמוד', 0.43850409984588623),
 ('מגופי', 0.4371641278266907),
 ('שחידשה', 0.4355635643005371),
 ('בלימוד', 0.4355284571647

In [12]:
c.most_similar('שליט"א',topn=100)

[('נ"י', 0.8398326635360718),
 ('זצ"ל', 0.8169643878936768),
 ('זצלה"ה', 0.77635657787323),
 ('זצוקלה"ה', 0.7608287334442139),
 ('הי"ו', 0.7467962503433228),
 ('זצוק"ל', 0.7441444396972656),
 ('אדמו"ר', 0.7311767339706421),
 ('זצללה"ה', 0.728669285774231),
 ("ני'", 0.7255306839942932),
 ('אויערבך', 0.7126733064651489),
 ('אבד"ק', 0.7098629474639893),
 ('הגאב"ד', 0.7069588899612427),
 ('הרצוג', 0.704680323600769),
 ('זצל"ה', 0.7021262645721436),
 ('יצ"ו', 0.6957736015319824),
 ('אויערבאך', 0.6914435625076294),
 ("שיחי'", 0.6900763511657715),
 ("שי'", 0.6884883046150208),
 ('דק"ק', 0.6868494153022766),
 ('זללה"ה', 0.6861818432807922),
 ('ד"ר', 0.6792221069335938),
 ('לכ"ק', 0.6769386529922485),
 ('הגרי"י', 0.6746237277984619),
 ('לאי"ט', 0.6682618856430054),
 ('האדמו"ר', 0.6678314208984375),
 ('אונטרמן', 0.6670634746551514),
 ('ידידנו', 0.6663059592247009),
 ('נר"י', 0.6637826561927795),
 ('רי"י', 0.6634947061538696),
 ('אב"ד', 0.6601877808570862),
 ('סאטמאר', 0.6581071615219116),
 ('הה"

In [13]:
model["man"]

array([-1.3444709 , -0.80200994, -1.5716014 , -0.00670901,  3.266178  ,
        3.029568  ,  2.1280856 , -2.3225467 ,  0.6991925 , -1.8656472 ,
        0.7849576 ,  2.3986347 ,  3.042096  , -0.01677596,  1.2403557 ,
       -0.24350628,  2.318188  ,  0.46335596,  0.43479574, -2.5434728 ,
        1.1667706 ,  3.0344737 , -0.1156328 , -1.1557214 , -1.6920861 ,
        1.800754  ,  1.8573644 , -0.19712588, -2.9661024 , -0.07013469,
       -0.563859  ,  1.3108822 , -0.3183852 , -0.9724901 , -0.6046136 ,
        1.054102  , -1.4615935 ,  0.2269479 ,  0.51800686, -2.4333036 ,
        0.02812001,  1.4467556 ,  0.4009765 ,  0.9999616 ,  0.02180146,
       -2.297916  ,  1.2079191 ,  0.45965922,  0.09886882,  1.6483984 ,
       -0.39067367, -0.25587636,  0.0589155 ,  0.25471637, -0.46753368,
        0.6133801 , -0.57133365, -0.90219104, -2.8167949 , -0.2962204 ,
       -1.9157574 , -1.0399828 ,  0.7730799 , -2.8992689 ,  1.2423402 ,
        0.6982486 ,  0.9294112 ,  1.1919203 ,  0.5904553 , -1.35

In [14]:
c.most_similar("איש",topn=100)

[('נעוריו', 0.7546830177307129),
 ('כאיש', 0.6756651401519775),
 ('רעהו', 0.6628029346466064),
 ('ואיש', 0.6517789959907532),
 ('פריץ', 0.6348031163215637),
 ('נעוריך', 0.6286264061927795),
 ('מאיש', 0.6261695623397827),
 ('לאיש', 0.6187355518341064),
 ('באיש', 0.6126406192779541),
 ('חורגו', 0.6117805242538452),
 ('אח', 0.6058979034423828),
 ('בחור', 0.604290246963501),
 ('דאיש', 0.6033228635787964),
 ('שאיש', 0.5832636952400208),
 ('פוטיפר', 0.5816781520843506),
 ('נער', 0.5722090005874634),
 ('האיש', 0.5681999921798706),
 ('נעורים', 0.5680266618728638),
 ('הפרופסור', 0.5527611970901489),
 ('יהודי', 0.549822986125946),
 ('יאודי', 0.548933744430542),
 ('כהן', 0.5450826287269592),
 ('חיל', 0.5351244807243347),
 ('נכריה', 0.5346681475639343),
 ("אורי'", 0.5346205234527588),
 ('נואף', 0.5287423133850098),
 ('כומר', 0.5199365615844727),
 ('יעל', 0.5184357166290283),
 ('אחיו', 0.5184255838394165),
 ('חותנתו', 0.5158212184906006),
 ('גלעזר', 0.5108785629272461),
 ('חמיו', 0.5091767907142639

In [15]:
c["איש"]

array([ 1.1370378 , -0.06798691, -3.02485   ,  1.0653871 , -0.04220054,
        0.30067867, -0.84371036,  3.2421875 ,  1.8027766 , -0.5122837 ,
        3.4504662 ,  0.8195233 ,  1.2115295 ,  0.10266535,  1.906915  ,
       -3.9729078 , -3.4402132 , -3.1017475 , -0.5412253 , -1.1571743 ,
        2.2348287 ,  0.26821283,  0.17182754,  3.5381272 , -3.0914721 ,
        0.14491369,  1.0027921 ,  2.407585  ,  2.0877168 , -3.3845732 ,
       -0.38371822,  1.4141043 ,  0.3232877 ,  1.1354258 , -1.6545204 ,
       -0.07984962,  2.853756  ,  1.3012354 ,  3.434358  ,  1.1791629 ,
        2.2992373 , -2.3519645 , -0.9935815 ,  4.8162694 , -0.95507854,
        3.146577  , -3.9064748 ,  0.7410461 ,  1.7669172 ,  0.8537286 ,
        2.8162613 , -1.7878228 ,  0.47128364,  0.9430283 ,  0.99119383,
       -0.43002787,  0.8539187 ,  1.2589198 , -1.4064138 ,  1.3873802 ,
       -5.673879  ,  1.699799  ,  1.0791022 , -3.1576703 ,  1.5558149 ,
        3.7600148 , -0.57720727, -0.13014434,  2.6265235 ,  4.34

In [16]:
model.most_similar("man")

[('woman', 0.7332974672317505),
 ('girl', 0.6301150918006897),
 ('creature', 0.5834453701972961),
 ('boy', 0.5702105760574341),
 ('evil', 0.5682586431503296),
 ('stranger', 0.559065043926239),
 ('person', 0.5582913160324097),
 ('god', 0.5446943044662476),
 ('mortal', 0.5428541898727417),
 ('gentleman', 0.5372711420059204)]

In [17]:
model.wv.most_similar(positive=["king","women"],negative=["men"])

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('queen', 0.6727709174156189),
 ('prince', 0.5837145447731018),
 ('throne', 0.5760980248451233),
 ('emperor', 0.5641942024230957),
 ('scotland', 0.5566437244415283),
 ('monarch', 0.5453583598136902),
 ('elizabeth', 0.5312689542770386),
 ('regent', 0.5301728248596191),
 ('crown', 0.5242427587509155),
 ('princess', 0.5089536905288696)]

In [18]:
model.wv.most_similar("frog")

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('shark', 0.8175339698791504),
 ('crab', 0.7895512580871582),
 ('pink', 0.7871852517127991),
 ('rat', 0.7829428911209106),
 ('feather', 0.7730915546417236),
 ('rabbit', 0.7726550698280334),
 ('swan', 0.7652913928031921),
 ('plum', 0.7609038949012756),
 ('purple', 0.7549035549163818),
 ('ginger', 0.7519762516021729)]

In [19]:
model.wv.most_similar("superman")

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('luthor', 0.8649570941925049),
 ('batman', 0.8550717830657959),
 ('villain', 0.7896559238433838),
 ('storyline', 0.788565993309021),
 ('lex', 0.7768101692199707),
 ('lois', 0.7737244367599487),
 ('marvel', 0.7463052272796631),
 ('daredevil', 0.7285870313644409),
 ('frankenstein', 0.7271486520767212),
 ('superhero', 0.7244809865951538)]

In [20]:
c.wv.most_similar("צפרדע")

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


[('וברה"י', 0.6846219897270203),
 ('טהור', 0.6432584524154663),
 ('טמא', 0.6353461742401123),
 ('ברה"י', 0.620927631855011),
 ('בטהור', 0.6134387254714966),
 ('וטמא', 0.5989843606948853),
 ('לטהור', 0.5928696393966675),
 ('שרץ', 0.5894265174865723),
 ('ונמרים', 0.5863572359085083),
 ('דאיטמא', 0.5858782529830933)]

In [21]:
v=c["איש"]

In [23]:
harryModel = gensim.models.Word2Vec.load("harry2vec.w2v")

In [24]:
harry.most_similar("azkaban")

NameError: name 'harry' is not defined

In [ ]:
harry.wv.most_similar("potter")

In [25]:
harry.wv.most_similar([ "dumbeldor","snap"])

NameError: name 'harry' is not defined

In [26]:
from gensim.models import Word2Vec
from sklearn.decomposition import PCA
from matplotlib import pyplot


In [27]:
X = model.wv[model.wv.vocab]


C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


In [28]:
X


array([[ 1.48711884e+00,  4.26511496e-01, -1.14349663e+00, ...,
         9.54478681e-02,  3.82412076e-01,  5.57495594e-01],
       [ 1.51484501e+00,  1.92826122e-01, -5.90856314e-01, ...,
        -8.73089731e-01, -9.74171758e-01,  6.07453823e-01],
       [ 9.05884802e-02,  6.46306992e-01, -8.63712847e-01, ...,
        -1.22507691e-01,  1.23450115e-01,  1.39470458e-01],
       ...,
       [ 3.12614888e-02,  8.89185220e-02,  6.19134353e-03, ...,
        -1.61708018e-03, -3.46111991e-02,  6.47023460e-03],
       [-5.61391972e-02, -1.01608010e-02,  2.69013513e-02, ...,
         5.68549288e-03,  5.58197871e-02, -5.08378446e-02],
       [-4.67266142e-02,  6.29410706e-03,  1.50924269e-02, ...,
         8.15506559e-03,  6.69251243e-03,  1.29830255e-03]], dtype=float32)

In [29]:
pca = PCA(n_components=2)
result = pca.fit_transform(X)

pyplot.scatter(result[:, 0], result[:, 1])
words = list(model.wv.vocab)
for i, word in enumerate(words):
	pyplot.annotate(word, xy=(result[i, 0], result[i, 1]))
pyplot.gcf().set_size_inches((2^16-1, 2^16-1))   
pyplot.show()

pyplot.gcf().set_size_inches((20, 20))   
pyplot.show()

In [30]:
words

NameError: name 'words' is not defined

In [ ]:
a=[]

In [ ]:
a.append(c.wv["תורה"])

In [ ]:
a.append(c.wv["גמרא"])

In [ ]:
a

In [ ]:
c.wv.cosine_similarities(a[0])

In [ ]:
c.wv.evaluate_word_pairs(["תורה","גמרא"])

In [ ]:
def avgG(a):
    avargea=np.average(a, axis=0)
    arr=np.asarray(avargea)
    return arr

In [ ]:
arr=[[1,1,1],[2,2,2],[3,3,3]]

In [31]:
l=avgG(arr)

NameError: name 'avgG' is not defined

In [32]:
import numpy as np

In [33]:
print(l)

NameError: name 'l' is not defined

In [34]:
a= [c.wv["מימרא"], c.wv["משנה"], c.wv["תוספתא"], c.wv["ירושלמי"], c.wv['ש"ס'], c.wv["גמרא"], c.wv["תורה"]]

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


In [35]:
c.similar_by_vector( avgG(a),topn=800)

NameError: name 'avgG' is not defined

In [36]:
c.similarity(c.wv["תורה"],avgG(a))

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


NameError: name 'avgG' is not defined

In [37]:
l=avgG(a)
r=c.wv["תורה"]

NameError: name 'avgG' is not defined

In [38]:
l-r

NameError: name 'l' is not defined

In [39]:
r1=c.wv["ירושלמי"]

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


In [40]:
r1-r

NameError: name 'r' is not defined

In [41]:
c.

SyntaxError: invalid syntax (<ipython-input-41-cf463a5954f9>, line 1)

In [42]:
c

In [43]:
c.accuracy("תורה")

C:\Users\AVI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `accuracy` (Method will be removed in 4.0.0, use self.evaluate_word_analogies() instead).
  """Entry point for launching an IPython kernel.


FileNotFoundError: [Errno 2] No such file or directory: 'תורה'

In [44]:
tora=c["תורה"]

In [45]:
print(tora)

[-5.0906053  -1.4476619   0.44951594  0.34393975  3.315324   -1.2160697
 -2.3288767  -4.0948377   2.6557796   1.6241122   0.663316    5.115574
  0.66066575 -0.3838822  -1.8672519  -0.31712934 -3.8078945  -1.9605649
 -2.169097   -1.1370202   3.2984385   5.464639    1.735446    3.2867117
 -0.5742428   1.3788878  -1.0197278   1.0686721   0.42610002 -1.4406922
 -3.3187969  -4.6152267  -4.8588634   0.56578517  1.8763477   0.9253663
  0.24990003  2.543531    1.0426549  -0.7702      4.2114253   1.7500674
  1.5102624   0.91925406 -3.6443737  -1.2703073   2.3235397   1.2600052
  1.7847061  -0.94221175  2.0550222  -3.7084534   1.3770705   3.5587847
  2.5262535   3.1105926  -4.992802   -0.83856064  1.9702272   1.5804341
 -0.9968705   0.76287097 -1.1050817  -4.52461    -0.18854177 -2.3103306
 -0.63863367  1.0057629   0.04034145  7.658269    0.81451267 -1.615896
 -0.26090607 -3.1112583  -1.8565668  -0.2544972   2.5608585  -0.04363022
  4.2264357   3.0779405  -5.3581505  -0.6727268   2.205882    0.3

In [46]:
a= [c["מימרא"], c["משנה"], c["תוספתא"], c["ירושלמי"], c['ש"ס'], c["גמרא"], c["תורה"]]

In [47]:
counter =0
for element in c.similar_by_vector( avgG(a),topn=8000):
    counter+=1
    if element[0] == "תורה":
        print(counter)
        print(element)

NameError: name 'avgG' is not defined

In [48]:
print( c.similar_by_vector( avgG(a),topn=1)[0][0] == "ירושלמי")

NameError: name 'avgG' is not defined

In [49]:
tora/np.linalg.norm(tora)

array([-0.20553878, -0.05845094,  0.0181497 ,  0.01388695,  0.13385986,
       -0.04910015, -0.09403095, -0.16533357,  0.10723002,  0.06557532,
        0.02678211,  0.20654692,  0.02667511, -0.01549967, -0.07539234,
       -0.01280445, -0.15374792, -0.07915996, -0.08757968, -0.04590844,
        0.13317809,  0.22064081,  0.07007053,  0.1327046 , -0.02318568,
        0.05567411, -0.04117263,  0.04314881,  0.01720426, -0.05816953,
       -0.13400006, -0.18634485, -0.19618194,  0.0228442 ,  0.0757596 ,
        0.03736268,  0.01008999,  0.10269786,  0.04209834, -0.03109767,
        0.17004092,  0.07066089,  0.0609785 ,  0.03711589, -0.14714558,
       -0.05129005,  0.09381547,  0.0508741 ,  0.07205947, -0.03804284,
        0.08297378, -0.14973289,  0.05560074,  0.14368984,  0.10200026,
        0.12559359, -0.20158987, -0.03385781,  0.07955009,  0.06381176,
       -0.04024974,  0.03080175, -0.04461889, -0.1826861 , -0.00761258,
       -0.09328214, -0.02578554,  0.04060878,  0.00162883,  0.30

In [50]:
b=a.pop()

In [51]:
a

[array([ 0.6878687 , -2.5382142 , -2.3409333 , -2.4569309 ,  2.6417022 ,
        -0.19643208, -0.7782054 , -1.9700116 , -2.2174072 ,  3.6775115 ,
        -4.1138854 , -5.2224054 , -0.85460967,  0.5741472 ,  0.15314941,
         0.18804069,  0.79335237,  0.15465167,  0.36156148, -0.43436337,
         1.4349867 , -0.5507443 , -2.067616  , -1.5972928 ,  2.8407128 ,
        -0.08964176, -0.90388525, -0.30764654,  0.98882794,  4.8979573 ,
         1.8681101 ,  1.6835068 ,  1.5092171 , -2.4242346 ,  0.9868474 ,
         1.0547999 , -0.01454553,  1.6025238 , -1.0482258 ,  3.1924791 ,
         2.252529  ,  1.8686804 , -2.202562  , -0.24550554, -0.26370862,
         1.292801  ,  2.384971  ,  1.6284285 , -0.10395607, -1.4741342 ,
        -1.1835312 , -1.893598  ,  1.2502958 , -1.1833112 , -0.74191624,
         1.0034797 ,  3.247218  , -0.18570915, -0.8510181 ,  0.29367667,
        -2.1053348 ,  1.142728  ,  2.4281883 ,  1.0673249 ,  1.6928865 ,
         0.84329146,  2.5432026 , -0.03976677, -1.8

In [52]:
def normal(vec):
    return vec/np.linalg.norm(vec)

In [53]:
anorm=[normal(c["מימרא"]), normal(c["משנה"]), normal(c["תוספתא"]), normal(c["ירושלמי"]), normal(c['ש"ס']),normal( c["גמרא"]), normal(c["תורה"])]

In [54]:
arr=c.similar_by_vector( avgG(a),topn=100)

NameError: name 'avgG' is not defined

In [55]:
arr1

NameError: name 'arr1' is not defined

In [56]:
arrnorm=c.similar_by_vector( avgG(anorm),topn=20000)

NameError: name 'avgG' is not defined

In [57]:
def name_list(vec):
    res=[]
    for element in vec:
        res.append(element[0])
    return res
    

In [58]:
name_list(arr)

NameError: name 'arr' is not defined

In [59]:
arr1=c.similar_by_vector( normal(avgG(a)),topn=20000)
l1=[]
print("---- not in normal vec ----")
counter=0
for a in name_list(arr1):
    counter+=1
    if a not in name_list(arrnorm):
        print(a,counter)
        l1.append(a)
print("----- not in regular vec ----" )
l2=[]
counter=0
for a in name_list(arrnorm):
    counter+=1
    if a not in name_list(arr1):
        l2.append(a)
        print(a,counter)
print(len(l1))
print(len(l2))

NameError: name 'avgG' is not defined

In [60]:
a= [c["מימרא"], c["משנה"], c["תוספתא"], c["ירושלמי"], c['ש"ס'], c["גמרא"], c["תורה"]]
test=avgG(a)

NameError: name 'avgG' is not defined

In [61]:
np.dot(c["תורה"],test)/np.dot(np.linalg.norm(c["תורה"]),np.linalg.norm(test))

NameError: name 'test' is not defined

In [62]:
def normal_met(metrix):
    res=[]
    for element in metrix:
        res.append(normal(element))
    return res


In [63]:
import utils as ut

In [64]:
model.most_similar("cat")

[('dog', 0.8374767303466797),
 ('bird', 0.7949255704879761),
 ('ass', 0.7866759300231934),
 ('panda', 0.7846667766571045),
 ('bee', 0.7742646932601929),
 ('goat', 0.7700502872467041),
 ('pig', 0.7681283354759216),
 ('hamster', 0.7586252689361572),
 ('stuffed', 0.7490887641906738),
 ('blonde', 0.7423551082611084)]

In [65]:
model.most_similar("lion",topn=40)

[('wolf', 0.7657798528671265),
 ('keeper', 0.7656422853469849),
 ('lily', 0.7655724883079529),
 ('maiden', 0.7601549625396729),
 ('serpent', 0.7476400136947632),
 ('mighty', 0.7454603910446167),
 ('beast', 0.7451087832450867),
 ('warrior', 0.7384510040283203),
 ('underworld', 0.7356871962547302),
 ('legendary', 0.7344549298286438),
 ('bride', 0.7338451743125916),
 ('robe', 0.7304897308349609),
 ('bull', 0.7275494337081909),
 ('witch', 0.7267272472381592),
 ('diana', 0.7250527143478394),
 ('bearded', 0.7174782752990723),
 ('treasure', 0.7148751616477966),
 ('thor', 0.7082850933074951),
 ('devil', 0.7078745365142822),
 ('rabbit', 0.7076638340950012),
 ('grendel', 0.7046124935150146),
 ('mummy', 0.7040061950683594),
 ('purple', 0.7021288871765137),
 ('seal', 0.7012300491333008),
 ('goddess', 0.7010761499404907),
 ('eyed', 0.7006295323371887),
 ('cloak', 0.699198842048645),
 ('boar', 0.6990817785263062),
 ('swan', 0.6966557502746582),
 ('maid', 0.6957486867904663),
 ('clad', 0.695355176925

In [66]:
model.most_similar("tiger")

[('dragon', 0.7592946290969849),
 ('leopard', 0.719265341758728),
 ('ducks', 0.7127292156219482),
 ('rainbow', 0.6851233243942261),
 ('mascot', 0.6819925308227539),
 ('panda', 0.6754711270332336),
 ('komodo', 0.6744835376739502),
 ('feather', 0.6740977764129639),
 ('gila', 0.6738598942756653),
 ('mighty', 0.673789381980896)]

In [67]:
lst=[model["puma"],model["cat"],model["lion"],model["tiger"],model["lynx"]]

In [68]:
avglist=ut.avg_vec(lst)

In [69]:
model.similar_by_vector(avglist)

[('tiger', 0.8718687295913696),
 ('leopard', 0.8556321263313293),
 ('cat', 0.851192831993103),
 ('panda', 0.8155982494354248),
 ('ducks', 0.8058640956878662),
 ('rat', 0.805817723274231),
 ('dog', 0.8005187511444092),
 ('deer', 0.7996582984924316),
 ('goat', 0.7994146347045898),
 ('lion', 0.7966138124465942)]

In [77]:
gmodel=gensim.models.KeyedVectors.load_word2vec_format("T:\\47\\model.txt")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 97: invalid continuation byte

In [73]:
gmodel.vocab

{'also_ADV': <gensim.models.keyedvectors.Vocab at 0x1f4501734c8>,
 'one_NUM': <gensim.models.keyedvectors.Vocab at 0x1f4502d5f48>,
 'first_ADJ': <gensim.models.keyedvectors.Vocab at 0x1f4501730c8>,
 'year_NOUN': <gensim.models.keyedvectors.Vocab at 0x1f4502d5e88>,
 'include_VERB': <gensim.models.keyedvectors.Vocab at 0x1f450173b88>,
 'two_NUM': <gensim.models.keyedvectors.Vocab at 0x1f45017aa08>,
 'make_VERB': <gensim.models.keyedvectors.Vocab at 0x1f450173f08>,
 'use_VERB': <gensim.models.keyedvectors.Vocab at 0x1f45017aa88>,
 'time_NOUN': <gensim.models.keyedvectors.Vocab at 0x1f450173d08>,
 'become_VERB': <gensim.models.keyedvectors.Vocab at 0x1f45017aac8>,
 'take_VERB': <gensim.models.keyedvectors.Vocab at 0x1f450173888>,
 'play_VERB': <gensim.models.keyedvectors.Vocab at 0x1f45017ab88>,
 'new_ADJ': <gensim.models.keyedvectors.Vocab at 0x1f450173808>,
 'part_NOUN': <gensim.models.keyedvectors.Vocab at 0x1f45017aa48>,
 'know_VERB': <gensim.models.keyedvectors.Vocab at 0x1f44dc0a108>

In [74]:
model.vocab

{'the': <gensim.models.keyedvectors.Vocab at 0x1f448ddab08>,
 'of': <gensim.models.keyedvectors.Vocab at 0x1f448de9388>,
 'and': <gensim.models.keyedvectors.Vocab at 0x1f448ddab88>,
 'one': <gensim.models.keyedvectors.Vocab at 0x1f448de9488>,
 'in': <gensim.models.keyedvectors.Vocab at 0x1f448ddac08>,
 'a': <gensim.models.keyedvectors.Vocab at 0x1f448de9588>,
 'to': <gensim.models.keyedvectors.Vocab at 0x1f448ddac88>,
 'zero': <gensim.models.keyedvectors.Vocab at 0x1f448de9688>,
 'nine': <gensim.models.keyedvectors.Vocab at 0x1f448ddad08>,
 'two': <gensim.models.keyedvectors.Vocab at 0x1f448de9788>,
 'is': <gensim.models.keyedvectors.Vocab at 0x1f448ddad48>,
 'as': <gensim.models.keyedvectors.Vocab at 0x1f448de9888>,
 'eight': <gensim.models.keyedvectors.Vocab at 0x1f448ddadc8>,
 'for': <gensim.models.keyedvectors.Vocab at 0x1f448de9988>,
 's': <gensim.models.keyedvectors.Vocab at 0x1f448ddae48>,
 'five': <gensim.models.keyedvectors.Vocab at 0x1f448de9a08>,
 'three': <gensim.models.key

In [76]:
gmodel["life"]

KeyError: "word 'life' not in vocabulary"

In [ ]:
model = gensim.models.Word2Vec.load_word2vec_format('./model/GoogleNews-vectors-negative300.bin', binary=True) 